version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
