import type { CreateLanguageDto } from 'src/languages/dto/create-language.dto';

export const languages: CreateLanguageDto[] = [
  {
    code: 'aa',
    name: 'Afar',
    rtl: false,
    nativeName: 'Afar',
  },
  {
    code: 'ab',
    name: 'Abkhazian',
    rtl: false,
    nativeName: 'Аҧсуа',
  },
  {
    code: 'af',
    name: 'Afrikaans',
    rtl: false,
    nativeName: 'Afrikaans',
  },
  {
    code: 'ak',
    name: 'Akan',
    rtl: false,
    nativeName: 'Akana',
  },
  {
    code: 'am',
    name: 'Amharic',
    rtl: false,
    nativeName: 'አማርኛ',
  },
  {
    code: 'an',
    name: 'Aragonese',
    rtl: false,
    nativeName: 'Aragonés',
  },
  {
    code: 'ar',
    name: 'Arabic',
    rtl: true,
    nativeName: 'العربية',
  },
  {
    code: 'as',
    name: 'Assamese',
    rtl: false,
    nativeName: 'অসমীয়া',
  },
  {
    code: 'av',
    name: 'Avar',
    rtl: false,
    nativeName: 'Авар',
  },
  {
    code: 'ay',
    name: 'Aymara',
    rtl: false,
    nativeName: 'Aymar',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    rtl: false,
    nativeName: 'Azərbaycanca / آذربايجان',
  },
  {
    code: 'ba',
    name: 'Bashkir',
    rtl: false,
    nativeName: 'Башҡорт',
  },
  {
    code: 'be',
    name: 'Belarusian',
    rtl: false,
    nativeName: 'Беларуская',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    rtl: false,
    nativeName: 'Български',
  },
  {
    code: 'bh',
    name: 'Bihari',
    rtl: false,
    nativeName: 'भोजपुरी',
  },
  {
    code: 'bi',
    name: 'Bislama',
    rtl: false,
    nativeName: 'Bislama',
  },
  {
    code: 'bm',
    name: 'Bambara',
    rtl: false,
    nativeName: 'Bamanankan',
  },
  {
    code: 'bn',
    name: 'Bengali',
    rtl: false,
    nativeName: 'বাংলা',
  },
  {
    code: 'bo',
    name: 'Tibetan',
    rtl: false,
    nativeName: 'བོད་ཡིག / Bod skad',
  },
  {
    code: 'br',
    name: 'Breton',
    rtl: false,
    nativeName: 'Brezhoneg',
  },
  {
    code: 'bs',
    name: 'Bosnian',
    rtl: false,
    nativeName: 'Bosanski',
  },
  {
    code: 'ca',
    name: 'Catalan',
    rtl: false,
    nativeName: 'Català',
  },
  {
    code: 'ce',
    name: 'Chechen',
    rtl: false,
    nativeName: 'Нохчийн',
  },
  {
    code: 'ch',
    name: 'Chamorro',
    rtl: false,
    nativeName: 'Chamoru',
  },
  {
    code: 'co',
    name: 'Corsican',
    rtl: false,
    nativeName: 'Corsu',
  },
  {
    code: 'cr',
    name: 'Cree',
    rtl: false,
    nativeName: 'Nehiyaw',
  },
  {
    code: 'cs',
    name: 'Czech',
    rtl: false,
    nativeName: 'Česky',
  },
  {
    code: 'cu',
    name: 'Old Church Slavonic / Old Bulgarian',
    rtl: false,
    nativeName: 'словѣньскъ / slověnĭskŭ',
  },
  {
    code: 'cv',
    name: 'Chuvash',
    rtl: false,
    nativeName: 'Чăваш',
  },
  {
    code: 'cy',
    name: 'Welsh',
    rtl: false,
    nativeName: 'Cymraeg',
  },
  {
    code: 'da',
    name: 'Danish',
    rtl: false,
    nativeName: 'Dansk',
  },
  {
    code: 'de',
    name: 'German',
    rtl: false,
    nativeName: 'Deutsch',
  },
  {
    code: 'dv',
    name: 'Divehi',
    rtl: true,
    nativeName: 'ދިވެހިބަސް',
  },
  {
    code: 'dz',
    name: 'Dzongkha',
    rtl: false,
    nativeName: 'ཇོང་ཁ',
  },
  {
    code: 'ee',
    name: 'Ewe',
    rtl: false,
    nativeName: 'Ɛʋɛ',
  },
  {
    code: 'el',
    name: 'Greek',
    rtl: false,
    nativeName: 'Ελληνικά',
  },
  {
    code: 'en',
    name: 'English',
    rtl: false,
    nativeName: 'English',
  },
  {
    code: 'eo',
    name: 'Esperanto',
    rtl: false,
    nativeName: 'Esperanto',
  },
  {
    code: 'es',
    name: 'Spanish',
    rtl: false,
    nativeName: 'Español',
  },
  {
    code: 'et',
    name: 'Estonian',
    rtl: false,
    nativeName: 'Eesti',
  },
  {
    code: 'eu',
    name: 'Basque',
    rtl: false,
    nativeName: 'Euskara',
  },
  {
    code: 'fa',
    name: 'Persian',
    rtl: true,
    nativeName: 'فارسی',
  },
  {
    code: 'ff',
    name: 'Peul',
    rtl: false,
    nativeName: 'Fulfulde',
  },
  {
    code: 'fi',
    name: 'Finnish',
    rtl: false,
    nativeName: 'Suomi',
  },
  {
    code: 'fj',
    name: 'Fijian',
    rtl: false,
    nativeName: 'Na Vosa Vakaviti',
  },
  {
    code: 'fo',
    name: 'Faroese',
    rtl: false,
    nativeName: 'Føroyskt',
  },
  {
    code: 'fr',
    name: 'French',
    rtl: false,
    nativeName: 'Français',
  },
  {
    code: 'fy',
    name: 'West Frisian',
    rtl: false,
    nativeName: 'Frysk',
  },
  {
    code: 'ga',
    name: 'Irish',
    rtl: false,
    nativeName: 'Gaeilge',
  },
  {
    code: 'gd',
    name: 'Scottish Gaelic',
    rtl: false,
    nativeName: 'Gàidhlig',
  },
  {
    code: 'gl',
    name: 'Galician',
    rtl: false,
    nativeName: 'Galego',
  },
  {
    code: 'gn',
    name: 'Guarani',
    rtl: false,
    nativeName: "Avañe'ẽ",
  },
  {
    code: 'gu',
    name: 'Gujarati',
    rtl: false,
    nativeName: 'ગુજરાતી',
  },
  {
    code: 'gv',
    name: 'Manx',
    rtl: false,
    nativeName: 'Gaelg',
  },
  {
    code: 'ha',
    name: 'Hausa',
    rtl: true,
    nativeName: 'هَوُسَ',
  },
  {
    code: 'he',
    name: 'Hebrew',
    rtl: true,
    nativeName: 'עברית',
  },
  {
    code: 'hi',
    name: 'Hindi',
    rtl: false,
    nativeName: 'हिन्दी',
  },
  {
    code: 'ho',
    name: 'Hiri Motu',
    rtl: false,
    nativeName: 'Hiri Motu',
  },
  {
    code: 'hr',
    name: 'Croatian',
    rtl: false,
    nativeName: 'Hrvatski',
  },
  {
    code: 'ht',
    name: 'Haitian',
    rtl: false,
    nativeName: 'Krèyol ayisyen',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    rtl: false,
    nativeName: 'Magyar',
  },
  {
    code: 'hy',
    name: 'Armenian',
    rtl: false,
    nativeName: 'Հայերեն',
  },
  {
    code: 'hz',
    name: 'Herero',
    rtl: false,
    nativeName: 'Otsiherero',
  },
  {
    code: 'ia',
    name: 'Interlingua',
    rtl: false,
    nativeName: 'Interlingua',
  },
  {
    code: 'id',
    name: 'Indonesian',
    rtl: false,
    nativeName: 'Bahasa Indonesia',
  },
  {
    code: 'ie',
    name: 'Interlingue',
    rtl: false,
    nativeName: 'Interlingue',
  },
  {
    code: 'ig',
    name: 'Igbo',
    rtl: false,
    nativeName: 'Igbo',
  },
  {
    code: 'ii',
    name: 'Sichuan Yi',
    rtl: false,
    nativeName: 'ꆇꉙ / 四川彝语',
  },
  {
    code: 'ik',
    name: 'Inupiak',
    rtl: false,
    nativeName: 'Iñupiak',
  },
  {
    code: 'io',
    name: 'Ido',
    rtl: false,
    nativeName: 'Ido',
  },
  {
    code: 'is',
    name: 'Icelandic',
    rtl: false,
    nativeName: 'Íslenska',
  },
  {
    code: 'it',
    name: 'Italian',
    rtl: false,
    nativeName: 'Italiano',
  },
  {
    code: 'iu',
    name: 'Inuktitut',
    rtl: false,
    nativeName: 'ᐃᓄᒃᑎᑐᑦ',
  },
  {
    code: 'ja',
    name: 'Japanese',
    rtl: false,
    nativeName: '日本語',
  },
  {
    code: 'jv',
    name: 'Javanese',
    rtl: false,
    nativeName: 'Basa Jawa',
  },
  {
    code: 'ka',
    name: 'Georgian',
    rtl: false,
    nativeName: 'ქართული',
  },
  {
    code: 'kg',
    name: 'Kongo',
    rtl: false,
    nativeName: 'KiKongo',
  },
  {
    code: 'ki',
    name: 'Kikuyu',
    rtl: false,
    nativeName: 'Gĩkũyũ',
  },
  {
    code: 'kj',
    name: 'Kuanyama',
    rtl: false,
    nativeName: 'Kuanyama',
  },
  {
    code: 'kk',
    name: 'Kazakh',
    rtl: false,
    nativeName: 'Қазақша',
  },
  {
    code: 'kl',
    name: 'Greenlandic',
    rtl: false,
    nativeName: 'Kalaallisut',
  },
  {
    code: 'km',
    name: 'Cambodian',
    rtl: false,
    nativeName: 'ភាសាខ្មែរ',
  },
  {
    code: 'kn',
    name: 'Kannada',
    rtl: false,
    nativeName: 'ಕನ್ನಡ',
  },
  {
    code: 'ko',
    name: 'Korean',
    rtl: false,
    nativeName: '한국어',
  },
  {
    code: 'kr',
    name: 'Kanuri',
    rtl: false,
    nativeName: 'Kanuri',
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    rtl: true,
    nativeName: 'कश्मीरी / كشميري',
  },
  {
    code: 'ku',
    name: 'Kurdish',
    rtl: true,
    nativeName: 'Kurdî / كوردی',
  },
  {
    code: 'kv',
    name: 'Komi',
    rtl: false,
    nativeName: 'Коми',
  },
  {
    code: 'kw',
    name: 'Cornish',
    rtl: false,
    nativeName: 'Kernewek',
  },
  {
    code: 'ky',
    name: 'Kirghiz',
    rtl: false,
    nativeName: 'Kırgızca / Кыргызча',
  },
  {
    code: 'la',
    name: 'Latin',
    rtl: false,
    nativeName: 'Latina',
  },
  {
    code: 'lb',
    name: 'Luxembourgish',
    rtl: false,
    nativeName: 'Lëtzebuergesch',
  },
  {
    code: 'lg',
    name: 'Ganda',
    rtl: false,
    nativeName: 'Luganda',
  },
  {
    code: 'li',
    name: 'Limburgian',
    rtl: false,
    nativeName: 'Limburgs',
  },
  {
    code: 'ln',
    name: 'Lingala',
    rtl: false,
    nativeName: 'Lingála',
  },
  {
    code: 'lo',
    name: 'Laotian',
    rtl: false,
    nativeName: 'ລາວ / Pha xa lao',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    rtl: false,
    nativeName: 'Lietuvių',
  },
  {
    code: 'lv',
    name: 'Latvian',
    rtl: false,
    nativeName: 'Latviešu',
  },
  {
    code: 'mg',
    name: 'Malagasy',
    rtl: false,
    nativeName: 'Malagasy',
  },
  {
    code: 'mh',
    name: 'Marshallese',
    rtl: false,
    nativeName: 'Kajin Majel / Ebon',
  },
  {
    code: 'mi',
    name: 'Maori',
    rtl: false,
    nativeName: 'Māori',
  },
  {
    code: 'mk',
    name: 'Macedonian',
    rtl: false,
    nativeName: 'Македонски',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    rtl: false,
    nativeName: 'മലയാളം',
  },
  {
    code: 'mn',
    name: 'Mongolian',
    rtl: false,
    nativeName: 'Монгол',
  },
  {
    code: 'mo',
    name: 'Moldovan',
    rtl: false,
    nativeName: 'Moldovenească',
  },
  {
    code: 'mr',
    name: 'Marathi',
    rtl: false,
    nativeName: 'मराठी',
  },
  {
    code: 'ms',
    name: 'Malay',
    rtl: false,
    nativeName: 'Bahasa Melayu',
  },
  {
    code: 'mt',
    name: 'Maltese',
    rtl: false,
    nativeName: 'bil-Malti',
  },
  {
    code: 'my',
    name: 'Burmese',
    rtl: false,
    nativeName: 'Myanmasa',
  },
  {
    code: 'na',
    name: 'Nauruan',
    rtl: false,
    nativeName: 'Dorerin Naoero',
  },
  {
    code: 'nd',
    name: 'North Ndebele',
    rtl: false,
    nativeName: 'Sindebele',
  },
  {
    code: 'ne',
    name: 'Nepali',
    rtl: false,
    nativeName: 'नेपाली',
  },
  {
    code: 'ng',
    name: 'Ndonga',
    rtl: false,
    nativeName: 'Oshiwambo',
  },
  {
    code: 'nl',
    name: 'Dutch',
    rtl: false,
    nativeName: 'Nederlands',
  },
  {
    code: 'nn',
    name: 'Norwegian Nynorsk',
    rtl: false,
    nativeName: 'Norsk (nynorsk)',
  },
  {
    code: 'no',
    name: 'Norwegian',
    rtl: false,
    nativeName: 'Norsk (bokmål / riksmål)',
  },
  {
    code: 'nr',
    name: 'South Ndebele',
    rtl: false,
    nativeName: 'isiNdebele',
  },
  {
    code: 'nv',
    name: 'Navajo',
    rtl: false,
    nativeName: 'Diné bizaad',
  },
  {
    code: 'ny',
    name: 'Chichewa',
    rtl: false,
    nativeName: 'Chi-Chewa',
  },
  {
    code: 'oc',
    name: 'Occitan',
    rtl: false,
    nativeName: 'Occitan',
  },
  {
    code: 'oj',
    name: 'Ojibwa',
    rtl: false,
    nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin',
  },
  {
    code: 'om',
    name: 'Oromo',
    rtl: false,
    nativeName: 'Oromoo',
  },
  {
    code: 'or',
    name: 'Oriya',
    rtl: false,
    nativeName: 'ଓଡ଼ିଆ',
  },
  {
    code: 'os',
    name: 'Ossetian / Ossetic',
    rtl: false,
    nativeName: 'Иронау',
  },
  {
    code: 'pa',
    name: 'Panjabi / Punjabi',
    rtl: false,
    nativeName: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
  },
  {
    code: 'pi',
    name: 'Pali',
    rtl: false,
    nativeName: 'Pāli / पाऴि',
  },
  {
    code: 'pl',
    name: 'Polish',
    rtl: false,
    nativeName: 'Polski',
  },
  {
    code: 'ps',
    name: 'Pashto',
    rtl: true,
    nativeName: 'پښتو',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    rtl: false,
    nativeName: 'Português',
  },
  {
    code: 'qu',
    name: 'Quechua',
    rtl: false,
    nativeName: 'Runa Simi',
  },
  {
    code: 'rm',
    name: 'Raeto Romance',
    rtl: false,
    nativeName: 'Rumantsch',
  },
  {
    code: 'rn',
    name: 'Kirundi',
    rtl: false,
    nativeName: 'Kirundi',
  },
  {
    code: 'ro',
    name: 'Romanian',
    rtl: false,
    nativeName: 'Română',
  },
  {
    code: 'ru',
    name: 'Russian',
    rtl: false,
    nativeName: 'Русский',
  },
  {
    code: 'rw',
    name: 'Rwandi',
    rtl: false,
    nativeName: 'Kinyarwandi',
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    rtl: false,
    nativeName: 'संस्कृतम्',
  },
  {
    code: 'sc',
    name: 'Sardinian',
    rtl: false,
    nativeName: 'Sardu',
  },
  {
    code: 'sd',
    name: 'Sindhi',
    rtl: false,
    nativeName: 'सिनधि',
  },
  {
    code: 'se',
    name: 'Northern Sami',
    rtl: false,
    nativeName: 'Davvisámegiella',
  },
  {
    code: 'sg',
    name: 'Sango',
    rtl: false,
    nativeName: 'Sängö',
  },
  {
    code: 'sh',
    name: 'Serbo-Croatian',
    rtl: false,
    nativeName: 'Srpskohrvatski / Српскохрватски',
  },
  {
    code: 'si',
    name: 'Sinhalese',
    rtl: false,
    nativeName: 'සිංහල',
  },
  {
    code: 'sk',
    name: 'Slovak',
    rtl: false,
    nativeName: 'Slovenčina',
  },
  {
    code: 'sl',
    name: 'Slovenian',
    rtl: false,
    nativeName: 'Slovenščina',
  },
  {
    code: 'sm',
    name: 'Samoan',
    rtl: false,
    nativeName: 'Gagana Samoa',
  },
  {
    code: 'sn',
    name: 'Shona',
    rtl: false,
    nativeName: 'chiShona',
  },
  {
    code: 'so',
    name: 'Somalia',
    rtl: false,
    nativeName: 'Soomaaliga',
  },
  {
    code: 'sq',
    name: 'Albanian',
    rtl: false,
    nativeName: 'Shqip',
  },
  {
    code: 'sr',
    name: 'Serbian',
    rtl: false,
    nativeName: 'Српски',
  },
  {
    code: 'ss',
    name: 'Swati',
    rtl: false,
    nativeName: 'SiSwati',
  },
  {
    code: 'st',
    name: 'Southern Sotho',
    rtl: false,
    nativeName: 'Sesotho',
  },
  {
    code: 'su',
    name: 'Sundanese',
    rtl: false,
    nativeName: 'Basa Sunda',
  },
  {
    code: 'sv',
    name: 'Swedish',
    rtl: false,
    nativeName: 'Svenska',
  },
  {
    code: 'sw',
    name: 'Swahili',
    rtl: false,
    nativeName: 'Kiswahili',
  },
  {
    code: 'ta',
    name: 'Tamil',
    rtl: false,
    nativeName: 'தமிழ்',
  },
  {
    code: 'te',
    name: 'Telugu',
    rtl: false,
    nativeName: 'తెలుగు',
  },
  {
    code: 'tg',
    name: 'Tajik',
    rtl: false,
    nativeName: 'Тоҷикӣ',
  },
  {
    code: 'th',
    name: 'Thai',
    rtl: false,
    nativeName: 'ไทย / Phasa Thai',
  },
  {
    code: 'ti',
    name: 'Tigrinya',
    rtl: false,
    nativeName: 'ትግርኛ',
  },
  {
    code: 'tk',
    name: 'Turkmen',
    rtl: false,
    nativeName: 'Туркмен / تركمن',
  },
  {
    code: 'tl',
    name: 'Tagalog',
    rtl: false,
    nativeName: 'Tagalog',
  },
  {
    code: 'tn',
    name: 'Tswana',
    rtl: false,
    nativeName: 'Setswana',
  },
  {
    code: 'to',
    name: 'Tonga',
    rtl: false,
    nativeName: 'Lea Faka-Tonga',
  },
  {
    code: 'tr',
    name: 'Turkish',
    rtl: false,
    nativeName: 'Türkçe',
  },
  {
    code: 'ts',
    name: 'Tsonga',
    rtl: false,
    nativeName: 'Xitsonga',
  },
  {
    code: 'tt',
    name: 'Tatar',
    rtl: false,
    nativeName: 'Tatarça',
  },
  {
    code: 'tw',
    name: 'Twi',
    rtl: false,
    nativeName: 'Twi',
  },
  {
    code: 'ty',
    name: 'Tahitian',
    rtl: false,
    nativeName: 'Reo Mā`ohi',
  },
  {
    code: 'ug',
    name: 'Uyghur',
    rtl: false,
    nativeName: 'Uyƣurqə / ئۇيغۇرچە',
  },
  {
    code: 'uk',
    name: 'Ukrainian',
    rtl: false,
    nativeName: 'Українська',
  },
  {
    code: 'ur',
    name: 'Urdu',
    rtl: true,
    nativeName: 'اردو',
  },
  {
    code: 'uz',
    name: 'Uzbek',
    rtl: false,
    nativeName: 'Ўзбек',
  },
  {
    code: 've',
    name: 'Venda',
    rtl: false,
    nativeName: 'Tshivenḓa',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    rtl: false,
    nativeName: 'Việtnam',
  },
  {
    code: 'vo',
    name: 'Volapük',
    rtl: false,
    nativeName: 'Volapük',
  },
  {
    code: 'wa',
    name: 'Walloon',
    rtl: false,
    nativeName: 'Walon',
  },
  {
    code: 'wo',
    name: 'Wolof',
    rtl: false,
    nativeName: 'Wollof',
  },
  {
    code: 'xh',
    name: 'Xhosa',
    rtl: false,
    nativeName: 'isiXhosa',
  },
  {
    code: 'yi',
    name: 'Yiddish',
    rtl: true,
    nativeName: 'ייִדיש',
  },
  {
    code: 'yo',
    name: 'Yoruba',
    rtl: false,
    nativeName: 'Yorùbá',
  },
  {
    code: 'za',
    name: 'Zhuang',
    rtl: false,
    nativeName: 'Cuengh / Tôô / 壮语',
  },
  {
    code: 'zh',
    name: 'Chinese',
    rtl: false,
    nativeName: '中文',
  },
  {
    code: 'zu',
    name: 'Zulu',
    rtl: false,
    nativeName: 'isiZulu',
  },
  {
    code: 'nb',
    name: 'Norwegian Bokmål',
    rtl: false,
    nativeName: 'Norsk (bokmål)',
  },
];
